import { useEffect, useState, type FormEvent } from 'react';
import { createRole, deleteRole, fetchPermissions, fetchRoles, updateRole, type Permission, type Role } from '../../api/adminApi';
import type { ApiClientError } from '../../api/axiosClient';
import { ConfirmDialog, DataState, FormDialog, PageHeader } from '../../components/admin/AdminUi';
import { useAuth } from '../../context/AuthContext';

type Draft = { code: string; nameAr: string; nameEn: string; description: string; isActive: boolean; permissionIds: number[] };
const empty: Draft = { code: '', nameAr: '', nameEn: '', description: '', isActive: true, permissionIds: [] };

export default function RolesPage() {
  const { user, hasPermission } = useAuth();
  const canManage = user?.defaultOrganizationId !== null && user?.defaultOrganizationId !== undefined
    && hasPermission('roles.manage', user.defaultOrganizationId);
  const [roles, setRoles] = useState<Role[]>([]); const [permissions, setPermissions] = useState<Permission[]>([]);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [editing, setEditing] = useState<Role | null | undefined>(); const [deleting, setDeleting] = useState<Role | null>(null);
  const [draft, setDraft] = useState<Draft>(empty); const [saving, setSaving] = useState(false); const [formError, setFormError] = useState('');
  const load = () => { setLoading(true); setError(''); Promise.all([fetchRoles(), fetchPermissions()]).then(([nextRoles, nextPermissions]) => { setRoles(nextRoles); setPermissions(nextPermissions); }).catch((e: ApiClientError) => setError(e.message)).finally(() => setLoading(false)); };
  useEffect(load, []);
  const open = (role?: Role) => { setEditing(role ?? null); setFormError(''); setDraft(role ? { code: role.code, nameAr: role.nameAr, nameEn: role.nameEn || '', description: role.description || '', isActive: role.isActive, permissionIds: role.permissions.map((p) => p.id) } : empty); };
  const submit = async (event: FormEvent) => { event.preventDefault(); setFormError(''); if (!draft.nameAr.trim() || (!editing && !draft.code.trim())) { setFormError('الاسم والرمز مطلوبان.'); return; } setSaving(true); try { if (editing) await updateRole(editing.id, { nameAr: draft.nameAr, nameEn: draft.nameEn || null, description: draft.description || null, isActive: draft.isActive, permissionIds: draft.permissionIds }); else await createRole({ code: draft.code, nameAr: draft.nameAr, nameEn: draft.nameEn || null, description: draft.description || null, permissionIds: draft.permissionIds }); setEditing(undefined); load(); } catch (e) { setFormError((e as ApiClientError).message); } finally { setSaving(false); } };
  const remove = async () => { if (!deleting) return; try { await deleteRole(deleting.id); setDeleting(null); load(); } catch (e) { setError((e as ApiClientError).message); setDeleting(null); } };
  return <><PageHeader title="الأدوار والصلاحيات" description="إدارة الأدوار المخصصة للمؤسسة والصلاحيات المرتبطة بها." actions={canManage && <button className="btn btn-primary" onClick={() => open()}>إضافة دور</button>} /><DataState loading={loading} error={error} empty={!roles.length} onRetry={load}><div className="card admin-table-card"><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>الدور</th><th>الرمز</th><th>الصلاحيات</th><th>الحالة</th>{canManage && <th>إجراءات</th>}</tr></thead><tbody>{roles.map(role => <tr key={role.id}><td><strong>{role.nameAr}</strong>{role.isSystem && <small className="admin-muted"> نظامي</small>}</td><td dir="ltr">{role.code}</td><td>{role.permissions.length}</td><td><span className={`admin-status-pill ${role.isActive ? 'is-success' : ''}`}>{role.isActive ? 'نشط' : 'معطّل'}</span></td>{canManage && <td className="admin-actions"><button className="btn btn-outline" onClick={() => open(role)}>تعديل</button>{!role.isSystem && <button className="admin-text-button danger" onClick={() => setDeleting(role)}>حذف</button>}</td>}</tr>)}</tbody></table></div></div></DataState>{editing !== undefined && canManage && <FormDialog title={editing ? 'تعديل الدور' : 'إضافة دور'} onClose={() => setEditing(undefined)} onSubmit={submit} saving={saving} error={formError}><div className="admin-form-grid">{!editing && <label className="field">الرمز<input dir="ltr" value={draft.code} onChange={e => setDraft({ ...draft, code: e.target.value })} required pattern="[a-z0-9_]+" /></label>}<label className="field">الاسم بالعربية<input value={draft.nameAr} onChange={e => setDraft({ ...draft, nameAr: e.target.value })} required /></label><label className="field">الاسم بالإنجليزية<input dir="ltr" value={draft.nameEn} onChange={e => setDraft({ ...draft, nameEn: e.target.value })} /></label><label className="field admin-field--full">الوصف<textarea value={draft.description} onChange={e => setDraft({ ...draft, description: e.target.value })} /></label><label className="admin-check"><input type="checkbox" checked={draft.isActive} onChange={e => setDraft({ ...draft, isActive: e.target.checked })} /> نشط</label><fieldset className="admin-field--full"><legend>الصلاحيات</legend><div className="admin-check-grid">{permissions.map(p => <label className="admin-check" key={p.id}><input type="checkbox" checked={draft.permissionIds.includes(p.id)} onChange={e => setDraft({ ...draft, permissionIds: e.target.checked ? [...draft.permissionIds, p.id] : draft.permissionIds.filter(id => id !== p.id) })} /> <span><b dir="ltr">{p.code}</b>{p.descriptionAr && <small>{p.descriptionAr}</small>}</span></label>)}</div></fieldset></div></FormDialog>}{deleting && canManage && <ConfirmDialog title="حذف الدور" message={`سيُحذف الدور «${deleting.nameAr}» نهائياً إذا لم يكن مستخدماً.`} onClose={() => setDeleting(null)} onConfirm={remove} />}</>;
}
