import { useEffect,useState,type FormEvent } from 'react';
import { createSlaRule,evaluateSla,fetchSlaRules,updateSlaRule,type SlaRule } from '../../api/adminApi';
import type { ApiClientError } from '../../api/axiosClient';import { DataState,FormDialog,PageHeader } from '../../components/admin/AdminUi';
import { formatDateTime } from '../../utils/dateTime';
type Draft={name:string;complaintType:string;firstResponseHours:string;resolutionHours:string;escalationIntervalHours:string;maxEscalationLevel:string;isActive:boolean};const empty:Draft={name:'',complaintType:'',firstResponseHours:'24',resolutionHours:'72',escalationIntervalHours:'24',maxEscalationLevel:'3',isActive:true};

export default function SlaPage() {
  const [items, setItems] = useState<SlaRule[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [editing, setEditing] = useState<SlaRule | null | undefined>();
  const [draft, setDraft] = useState<Draft>(empty);
  const [saving, setSaving] = useState(false);
  const [formError, setFormError] = useState('');
  const [evaluation, setEvaluation] = useState('');
  const load = () => { setLoading(true); fetchSlaRules().then(setItems).catch((e: ApiClientError) => setError(e.message)).finally(() => setLoading(false)); };
  useEffect(load, []);
  const open = (rule?: SlaRule) => { setEditing(rule ?? null); setFormError(''); setDraft(rule ? { name: rule.name, complaintType: rule.complaintType || '', firstResponseHours: String(rule.firstResponseHours), resolutionHours: String(rule.resolutionHours), escalationIntervalHours: String(rule.escalationIntervalHours), maxEscalationLevel: String(rule.maxEscalationLevel), isActive: rule.isActive } : empty); };
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); const payload = { name: draft.name, complaintType: draft.complaintType || null, firstResponseHours: Number(draft.firstResponseHours), resolutionHours: Number(draft.resolutionHours), escalationIntervalHours: Number(draft.escalationIntervalHours), maxEscalationLevel: Number(draft.maxEscalationLevel), isActive: draft.isActive }; try { if (editing) await updateSlaRule(editing.id, payload); else await createSlaRule(payload); setEditing(undefined); load(); } catch (e) { setFormError((e as ApiClientError).message); } finally { setSaving(false); } };
  const runEvaluation = async () => { setEvaluation(''); try { const result = await evaluateSla(); setEvaluation(`تم تقييم ${result.evaluated} طلب؛ المتأخر: ${result.overdue}، والمصعّد: ${result.escalated}.`); } catch (e) { setError((e as ApiClientError).message); } };
  return <><PageHeader title="قواعد مهلة المعالجة (SLA)" description="قواعد زمن الاستجابة والحل والتصعيد الفعلية." actions={<span className="admin-actions"><button className="btn btn-outline" onClick={runEvaluation}>تقييم SLA</button><button className="btn btn-primary" onClick={() => open()}>إضافة قاعدة</button></span>} />
    {evaluation && <div className="admin-success" role="status">{evaluation}</div>}
    <DataState loading={loading} error={error} empty={!items.length} onRetry={load}><div className="card admin-table-card"><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>القاعدة</th><th>النوع</th><th>استجابة أولى</th><th>الحل</th><th>التصعيد</th><th>الحالة</th><th>آخر تحديث</th><th>إجراء</th></tr></thead><tbody>{items.map(item => <tr key={item.id}><td>{item.name}</td><td>{item.complaintType === 'complaint' ? 'شكوى' : item.complaintType === 'proposal' ? 'مقترح' : 'كل الأنواع'}</td><td>{item.firstResponseHours} ساعة</td><td>{item.resolutionHours} ساعة</td><td>{item.escalationIntervalHours} ساعة</td><td><span className={`admin-status-pill ${item.isActive ? 'is-success' : ''}`}>{item.isActive ? 'نشطة' : 'معطلة'}</span></td><td>{formatDateTime(item.updatedAt)}</td><td><button className="btn btn-outline" onClick={() => open(item)}>تعديل</button></td></tr>)}</tbody></table></div></div></DataState>
    {editing !== undefined && <FormDialog title={editing ? 'تعديل قاعدة SLA' : 'إضافة قاعدة SLA'} onClose={() => setEditing(undefined)} onSubmit={submit} saving={saving} error={formError}><div className="admin-form-grid"><label className="field">اسم القاعدة<input value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })} required /></label><label className="field">نوع الطلب<select value={draft.complaintType} onChange={e => setDraft({ ...draft, complaintType: e.target.value })}><option value="">كل الأنواع</option><option value="complaint">شكوى</option><option value="proposal">مقترح</option></select></label><label className="field">ساعات الاستجابة الأولى<input type="number" min="1" value={draft.firstResponseHours} onChange={e => setDraft({ ...draft, firstResponseHours: e.target.value })} required /></label><label className="field">ساعات الحل<input type="number" min="1" value={draft.resolutionHours} onChange={e => setDraft({ ...draft, resolutionHours: e.target.value })} required /></label><label className="field">فاصل التصعيد<input type="number" min="1" value={draft.escalationIntervalHours} onChange={e => setDraft({ ...draft, escalationIntervalHours: e.target.value })} required /></label><label className="field">الحد الأقصى للتصعيد<input type="number" min="1" max="10" value={draft.maxEscalationLevel} onChange={e => setDraft({ ...draft, maxEscalationLevel: e.target.value })} required /></label><label className="admin-check"><input type="checkbox" checked={draft.isActive} onChange={e => setDraft({ ...draft, isActive: e.target.checked })} /> نشطة</label></div></FormDialog>}</>;
}
